name: merchant
channels:
  - defaults
  - conda-forge
  - glemaitre 
dependencies:
  - click=6.7
  - cycler=0.10.0
  - dbus=1.10.20
  - decorator=4.1.2
  - expat=2.1.0
  - filelock=2.0.7
  - flask=0.12.2
  - flask-cors=3.0.3
  - fontconfig=2.12.1
  - freetype=2.5.5
  - glib=2.50.2
  - gst-plugins-base=1.8.0
  - gstreamer=1.8.0
  - icu=54.1
  - imbalanced-learn=0.2.1
  - ipdb=0.10.3
  - ipython=6.1.0
  - ipython_genutils=0.2.0
  - itsdangerous=0.24
  - jedi=0.10.2
  - jinja2=2.9.6
  - jpeg=9b
  - libffi=3.2.1
  - libgcc=5.2.0
  - libgfortran=3.0.0
  - libiconv=1.14
  - libpng=1.6.27
  - libxcb=1.12
  - libxml2=2.9.4
  - line_profiler=2.0
  - markupsafe=0.23
  - matplotlib=2.0.2
  - mkl=2017.0.3
  - numpy=1.13.1
  - openssl=1.0.2l
  - pandas=0.20.3
  - path.py=10.3.1
  - pcre=8.39
  - pexpect=4.2.1
  - pickleshare=0.7.4
  - pip=9.0.1
  - prompt_toolkit=1.0.14
  - ptyprocess=0.5.2
  - pygments=2.2.0
  - pyparsing=2.2.0
  - pyqt=5.6.0
  - python=3.5.2
  - python-dateutil=2.6.1
  - pytz=2017.2
  - qt=5.6.2
  - readline=6.2
  - requests=2.14.2
  - scikit-learn=0.19.0
  - scipy=0.19.1
  - setuptools=27.2.0
  - simplegeneric=0.8.1
  - sip=4.18
  - six=1.10.0
  - sqlite=3.13.0
  - tk=8.5.18
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - werkzeug=0.12.2
  - wheel=0.29.0
  - xgboost=0.6a2
  - xz=5.2.2
  - zlib=1.2.8